name: B2CPolicyDeployment-Dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  DEV:
    # The type of runner that the job will run on
    if: github.ref_name == 'dev' # This job will run only if the workflow is triggered against the 'dev' branch.
    runs-on: ubuntu-latest
    environment: Development # This job depends upon the 'Dev' GitHub environment from where the job loads the workflow variables.

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # - uses: actions/checkout@v3
      #   with:
      #     repository: WhoIAM-Development/WhoIAmB2CLocalizationTool

      # - name: Archive artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: localizationTool
      #     path: |
      #       *    
            
      - uses: actions/checkout@v3
      
      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '{Settings:'
          tokenSuffix: '}'
          files: '["**/*.xml"]'
        env: # These variables are expected to be present in the GitHub environment.
          PolicySet: ${{ vars.POLICYSET }}
          TenantShort: ${{ vars.TENANTSHORT }}
          TenantGuid: ${{ vars.TENANTGUID }}
          AzureIEFAppId: ${{ vars.AZUREIEFAPPID }}
          AzureProxyIEFAppId: ${{ vars.AZUREPROXYIEFAPPID }}
          ExtensionsAppId: ${{ vars.EXTENSIONSAPPID }}
          ExtensionsAppObjectId: ${{ vars.EXTENSIONSAPPOBJECTID }}
          AppInsightsInstrumentationKey: ${{ vars.APPINSIGHTSINSTRUMENTATIONKEY }}
          AppInsightsDeveloperMode: ${{ vars.APPINSIGHTSDEVELOPERMODE }}
          AppInsightsDisableTelemetry: ${{ vars.APPINSIGHTSDISABLETELEMETRY }}
          DeploymentMode: ${{ vars.DEPLOYMENTMODE }}
          ScriptExecutionElement: ${{ vars.SCRIPTEXECUTIONELEMENT }}
          UIBaseUrl: ${{ vars.UIBASEURL }}
          DFPInstanceId: ${{ vars.DFPINSTANCEID }}
          IntermediateAppUrl: ${{ vars.INTERMEDIATEAPPURL }}
          IntermediateApiAccessTokenTenantShort: ${{ vars.INTERMEDIATEAPIACCESSTOKENTENANTSHORT }}
          IntermediateApiAccessTokenClientIdName: ${{ vars.INTERMEDIATEAPIACCESSTOKENCLIENTIDNAME }}
          IntermediateApiAccessTokenClientSecretName: ${{ vars.INTERMEDIATEAPIACCESSTOKENCLIENTSECRETNAME }}
          IntermediateApiAccessTokenScope: ${{ vars.INTERMEDIATEAPIACCESSTOKENSCOPE }}

      # - name: Archive artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: policies
      #     path: |
      #       *     

      - name: 'Upload TrustFrameworkBase Policy'
        uses: azure-ad-b2c/deploy-trustframework-policy@v3
        with:
          folder: "Policies"
          # Specify all the policies to be deployed as comma separated. The workflow deploys the policies based on the order given here.
          files: "TrustFrameworkBase.xml,TrustFrameworkLocalization.xml,TrustFrameworkExtensions.xml,SignUpOrSignin.xml,ProfileEdit.xml,ChangeMfa.xml"
          tenant: ${{ vars.TENANT }}
          clientId: ${{ vars.POLICYDEPLOYAPPID }}
          clientSecret: '${{ secrets.POLICYDEPLOYAPPSECRET }}'