name: B2CPolicyDeployment-Prod

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  PRODUCTION:
      # The type of runner that the job will run on
      if: github.ref_name == 'main' # This job will run only if the workflow is triggered against the 'main' branch.
      runs-on: ubuntu-latest
      environment: Production # This job depends upon the 'Production' GitHub environment from where the job loads the workflow variables.

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3
        
        - uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '{Settings:'
            tokenSuffix: '}'
            files: '["**/*.xml"]'
          env: # These variables are expected to be present in the GitHub environment.
            PolicySet: ${{ vars.POLICYSET }}
            TenantShort: ${{ vars.TENANTSHORT }}
            TenantGuid: ${{ vars.TENANTGUID }}
            AzureIEFAppId: ${{ vars.AZUREIEFAPPID }}
            AzureProxyIEFAppId: ${{ vars.AZUREPROXYIEFAPPID }}
            ExtensionsAppId: ${{ vars.EXTENSIONSAPPID }}
            ExtensionsAppObjectId: ${{ vars.EXTENSIONSAPPOBJECTID }}
            AppInsightsInstrumentationKey: ${{ vars.APPINSIGHTSINSTRUMENTATIONKEY }}
            AppInsightsDeveloperMode: ${{ vars.APPINSIGHTSDEVELOPERMODE }}
            AppInsightsDisableTelemetry: ${{ vars.APPINSIGHTSDISABLETELEMETRY }}
            DeploymentMode: ${{ vars.DEPLOYMENTMODE }}
            ScriptExecutionElement: ${{ vars.SCRIPTEXECUTIONELEMENT }}
            UIBaseUrl: ${{ vars.UIBASEURL }}
            DFPInstanceId: ${{ vars.DFPINSTANCEID }}
            IntermediateAppUrl: ${{ vars.INTERMEDIATEAPPURL }}
            IntermediateApiAccessTokenTenantShort: ${{ vars.INTERMEDIATEAPIACCESSTOKENTENANTSHORT }}
            IntermediateApiAccessTokenClientIdName: ${{ vars.INTERMEDIATEAPIACCESSTOKENCLIENTIDNAME }}
            IntermediateApiAccessTokenClientSecretName: ${{ vars.INTERMEDIATEAPIACCESSTOKENCLIENTSECRETNAME }}
            IntermediateApiAccessTokenScope: ${{ vars.INTERMEDIATEAPIACCESSTOKENSCOPE }}

        - name: 'Upload TrustFrameworkBase Policy'
          uses: azure-ad-b2c/deploy-trustframework-policy@v3
          with:
            folder: "Policies"
            # Specify all the policies to be deployed as comma separated. The workflow deploys the policies based on the order given here.
            files: "TrustFrameworkBase.xml,TrustFrameworkLocalization.xml,TrustFrameworkExtensions.xml,SignUpOrSignin.xml"
            tenant: ${{ vars.TENANT }}
            clientId: ${{ vars.POLICYDEPLOYAPPID }}
            clientSecret: ${{ secrets.POLICYDEPLOYAPPSECRET }}
